This directory has Xray spectra generated by Scott Wilderman
(using some type of Monte Carlo program I think).
The units of the spectra are Xray-photons / mAs-sr-keV, so for a typical
detector that produces a signal that is proportional to energy, we need to
multiply these spectra by the energies.  It would also be desirable to
include the energy-dependent absorption properties of the detector.

These spectra only include the inherent filtering that is present in the
X-ray source itself.  For realistic use we must also add some filters.

each of the spectra.* files had the following 3 lines at the bottom
that i removed manually:
	Attenuation History:
	1
	beryllium 0.500000

Note added 2010-04-07:
I think that the units "photons / mAs-sr-keV" probably should be interpreted
as "photons / mAs-sr per energy bin"

-----------------------------------------------------------------

xtube.tar.gz (and spectra.*) came from neal's ftp site:
	ftp://141.214.74.79

Neal Clinthorne says:
For filtration, probably should use at least 2.5 mm Al for low energy and an
additional 0.5 mm Cu for higher E.  (Of course you can play games with other
materials also such as Mo and Sn, but I don't think there's much need to at
this point.)

sr - steradian 

Here's Scott Wilderman's email describing the format:

Attached is a tar file with spectra from the older version of our program for
a tungsten anode tube, 40 degree target angle, constant potential generator,
with .5 mm Be inherent filtration.

The files are labeled spectra.20 -> spectra.160, and look like:

spect_gen: 74  40.000  1     20.000
   20     1.000      0.0000
    Energy   #/mAs-sr-keV
      1.000     0.0000E+00
      2.000     1.4888E-05
Attenuation History:
   1
beryllium              0.500000

The parameters on the first line are:

spect_gen: 74  40.000  1     20.000
            Z  angle  wave    kVp
                      form
second line:
   20     1.000      0.0000
  #bins   bin width  source-distance

Then comes the spectrum, photons/mAs-sr-keV, and then the attenuation history.

-----------------------------------------------------------------

Tue Apr 24 21:46:30 EDT 2001
xray080.mat xray140.mat
These source spectra were sent by Predrag Sukovic,
modified from those of Scott Wilderman.

Predrag applied filtration of 1mm of Al and .5mm of Cu.
He also took into account the absorption properties of the screen
used in his detector so that the spectra are as close as possible
to what is detected by his particular detector.

-----------------------------------------------------------------
