% test_all_graph

list = {...
'cbar test', ...
'im test', ...
'im_toggle test', ...
'jf_add_slider test', ...
'jf_mip3 test', ...
'montager test', ...
'plot_cell test', ...
'plot_ellipse test', ...
'slicer3 test', ...
'subplot_stack test', ...
'texts test', ...
'xtick test', ...
};

if ~ir_is_octave
	list{end+1} = 'jf_slicer test'; % no scroll wheel
end

%'movie2 test', ...
%'ir_savefig test', ...

run_mfile_local(list)
