  function str = jf_hct_arg(pn, cg, ig)
%|function str = jf_hct_arg(pn, cg, ig)
%|
%| name/value pairs needed for hct command line
%|
%| Copyright 2009-11-21, Jeff Fessler, University of Michigan

str = [
	sprintf(' nx %d ny %d nz %d', ig.nx, ig.ny, ig.nz) ...
	sprintf(' dx %g dy %g dz %g', ig.dx, ig.dy, ig.dz) ...
	sprintf(' offset_x %.9e offset_y %.9e offset_z %.9e', ...
		ig.offset_x, ig.offset_y, ig.offset_z) ...
	sprintf(' ns %d nt %d na %d', cg.ns, cg.nt, cg.na) ...
	sprintf(' ds %.9e dt %.9e', cg.ds, cg.dt) ...
	sprintf(' offset_s %.9e offset_t %.9e', cg.offset_s, cg.offset_t) ...
	sprintf(' dfs %.9e dso %.9e dsd %.9e', cg.dfs, cg.dso, cg.dsd) ...
	sprintf(' orbit %.9e orbit_start %.9e', cg.orbit, cg.orbit_start) ...
	sprintf(' pitch %.9e source_z0 %.9e', cg.pitch, cg.source_z0) ...
];
